import { readFileSync, writeFileSync, readdirSync, mkdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";

const rootDir = join(dirname(import.meta.filename), "..");
const skillsDir = join(rootDir, "skills");
const outDir = join(rootDir, "src", "generated");
const outFile = join(outDir, "embedded-skills.ts");

mkdirSync(outDir, { recursive: true });

// Discover skills: each subdirectory of skills/ containing a SKILL.md
const skillDirs = readdirSync(skillsDir)
  .filter((name) => {
    const path = join(skillsDir, name);
    return statSync(path).isDirectory() && statSync(join(path, "SKILL.md"), { throwIfNoEntry: false })?.isFile();
  })
  .sort();

const entries: string[] = [];

for (const dir of skillDirs) {
  const content = readFileSync(join(skillsDir, dir, "SKILL.md"), "utf8");
  entries.push(`  ${JSON.stringify(dir)}: {
    filename: ${JSON.stringify(dir + ".md")},
    content: ${JSON.stringify(content)}
  }`);
}

const output = `// Auto-generated by scripts/embed-skills.ts — do not edit
export const EMBEDDED_SKILLS: Record<string, { filename: string; content: string }> = {
${entries.join(",\n")}
};
`;

writeFileSync(outFile, output);
console.log(`Embedded ${skillDirs.length} skill(s) into src/generated/embedded-skills.ts`);
