import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";

const rootDir = join(dirname(import.meta.filename), "..");
const skillsDir = join(rootDir, "skills");
const outDir = join(rootDir, "src", "generated");
const outFile = join(outDir, "embedded-skills.ts");

mkdirSync(outDir, { recursive: true });

const skillFiles = readdirSync(skillsDir).filter((f) => f.endsWith(".md")).sort();
const entries: string[] = [];

for (const file of skillFiles) {
  const content = readFileSync(join(skillsDir, file), "utf8");
  const key = basename(file, ".md");
  entries.push(`  ${JSON.stringify(key)}: {
    filename: ${JSON.stringify(file)},
    content: ${JSON.stringify(content)}
  }`);
}

const output = `// Auto-generated by scripts/embed-skills.ts — do not edit
export const EMBEDDED_SKILLS: Record<string, { filename: string; content: string }> = {
${entries.join(",\n")}
};
`;

writeFileSync(outFile, output);
console.log(`Embedded ${skillFiles.length} skill(s) into src/generated/embedded-skills.ts`);
