import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const rootDir = join(dirname(import.meta.filename), "..");
const skillsDir = join(rootDir, "skills");
const outDir = join(rootDir, "src", "generated");
const outFile = join(outDir, "embedded-skills.ts");

mkdirSync(outDir, { recursive: true });

const linearCli = readFileSync(join(skillsDir, "linear-cli.md"), "utf8");
const linearRawGql = readFileSync(join(skillsDir, "linear-raw-gql.md"), "utf8");

const content = `// Auto-generated by scripts/embed-skills.ts — do not edit
export const EMBEDDED_SKILLS: Record<string, { filename: string; content: string }> = {
  "linear-agent-cli": {
    filename: "linear-agent-cli.md",
    content: ${JSON.stringify(linearCli)}
  },
  "linear-agent-raw-gql": {
    filename: "linear-agent-raw-gql.md",
    content: ${JSON.stringify(linearRawGql)}
  }
};
`;

writeFileSync(outFile, content);
console.log("Embedded skills written to src/generated/embedded-skills.ts");
